### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by viciexperts** [hanc2006/google-coverage-parser#1]
Hello,
How can I use this to export green css in my website?

**Comment by hanc2006** [comment]
Hi,
this repository code is intended to use with chrome coverage tool. You first need to export the coverage results from google chrome browser [how-to](https://www.vojtechruzicka.com/measuring-javascript-and-css-coverage-with-google-chrome-developer-tools).

After you can replace the data folder content with your coverage files.

In the main code:

`Promise.all([`
  `import('./data/coverage_page1.js'),`
  `import('./data/coverage_page2.js'),`
`]).then((results) => {`

..replace the coverage example files paths with yours.

Open the browser and view the index.html page. The new cleaned CSS files will be created automatically (and zipped).

**Comment by viciexperts** [comment]
Thank you
